config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#welcome'

  get '/about' => 'static_pages#about'

  resources :recipes do
    member do
      post :unpublish
    end
  end

  get '/profile' => 'user#show'
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  before_save :downcase_fields

  has_many :recipe_items
  has_many :recipes, through: :recipe_items

  def downcase_fields
    self.name.downcase!
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user

  has_many :recipe_items
  has_many :ingredients, through: :recipe_items
  accepts_nested_attributes_for :recipe_items

  validates :title, presence: true
  validates :instructions, presence: true
  validates :recipe_items, presence: true

  def self.published_recipes
    Recipe.where("published = ?", true)
  end

  def self.unpublished_recipes
    Recipe.where("published =?", false)
  end
end

app/models/recipe_item.rb
class RecipeItem < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
  accepts_nested_attributes_for :ingredient

  validates :amount, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :prepare_unobtrusive_flash
end

app/controllers/recipe_items_controller.rb
class RecipeItemsController < ApplicationController
  def new
    @recipe_item = RecipeItem.new
    @recipe_item.build_ingredient
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @instructions = JSON.parse(@recipe.instructions)
  end

  def new
   @recipe = Recipe.new
   @recipe.recipe_items.build.build_ingredient
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @instructions = JSON.parse(@recipe.instructions)
  end

  def create
    params[:recipe][:instructions] = params[:recipe][:instructions].to_json
    @recipe = current_user.recipes.build(recipe_params)
    build_recipe_ingredients
    @recipe.published = true if params[:published] == "true"

    if @recipe.save
      redirect_to @recipe
    else
      render "new"
    end
  end

  def update
    params[:recipe][:instructions] = params[:recipe][:instructions].to_json
    @recipe = Recipe.find(params[:id])
    @recipe.published = true if params[:published] == "true"
    @recipe.toggle(:published) if params[:published] == "false"

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render "edit"
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path
  end

  def build_recipe_ingredients
    @recipe.recipe_items.each do |recipe_item|
      recipe_item.ingredient = Ingredient.find_or_create_by(name: recipe_item.ingredient.name)
    end
  end

  private
    def recipe_params
      params.require(:recipe).permit(:title, :instructions,
                                     recipe_items_attributes: [:id, :amount, ingredient_attributes:[:name]])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  end

  def about
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields",
                       data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="footer">
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<div class="unobtrusive-flash-container"></div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Recetera: a recipe app!', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recetera</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation"
      <h2>
        <%= pluralize(@recipe.errors.count, "error") %>
        prohibited this recipe from being saved:
      </h2>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end%>
      </ul>
    </div>
  <%end %>
  <div class="form-group">
    <%= f.label :title %>:
    <%= f.text_field :title, :class => 'form-control' %>

    <div id="ingredients">
      <label>Ingredients:</label>
        <%= f.fields_for :recipe_items do |builder| %>
        <%= render 'recipe_item_fields', f: builder %>
      <div id="links">
        <%= link_to_add_association "add Ingredient", f, :recipe_items %><br/>
      </div>
        <% end %>
    </div>

    <%= f.label :instructions %>:
    <% unless @instructions.nil? %>
      <% @instructions.each do |instruction| %>
        <%= text_field_tag 'recipe[instructions][]', instruction %>
      <% end %>
    <% else %>
      <%= text_field_tag 'recipe[instructions][]', nil, class: 'form-control', placeholder: 'Type the first step' %>
    <% end %>
    <div id="recipe_steps">
      <%= link_to "Remove Step", "javascript:void(0)", class: "remove_step" %>
    </div>
    <%= link_to "Next Step", "javascript:void(0)", id: "new_step" %><br/>
    <%= f.button "Publish", :name => "published", :value => "true" %>
    <%= f.button "Save Draft", :name => "published", :value => "false" %>
  </div>
<% end %>

app/views/recipes/_recipe_item_fields.html.erb
<div class="nested-fields form-inline">
  <%= f.label :amount %>
  <%= f.text_field :amount, :class => 'form-control' %>
  
  <% f.object.build_ingredient unless f.object.ingredient %>

  <%= f.fields_for :ingredient do |ff| %>
    <%= ff.label :name %>
    <%= ff.text_field :name, :class => 'form-control' %>
  <% end %>
  <%= link_to_remove_association "remove ingredient", f %>
</div>

app/views/recipes/edit.html.erb
<div class="container">
  <div class="jumbotron">
    <h1> Edit Recipe </h1>

    <%= render 'form' %>

    <%= link_to 'view all recipes', recipes_path %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h2 class="page-heading">List of Recipes</h2><br/>

    <table class="table table-condensed center-table">
      <tr>
        <th class="col-sm-2">Recipe#</th>
        <th class="col-sm-4">Title</th>
        <th class="col-sm-2">Link</th>
      </tr>

      <% @recipes.published_recipes.each_with_index do |recipe, i| %>
        <tr>
          <td><%= i+1 %></td>
          <td><%= recipe.title %></td>
          <td><%= link_to 'View Recipe', recipe_path(recipe) %></td>
        </tr>
      <% end %>
    </table>
    <br/>
    <%= link_to 'New recipe', new_recipe_path, :class => "btn btn-info" %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="jumbotron">
    <h2 class="page-heading">New Recipe</h2><br/>

    <%= render 'form' %>

    <%= link_to 'view all recipes', recipes_path %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="jumbotron">
      <h2 class="page-heading">
      <%= @recipe.title %>
    </h2>

    <p>
      <strong>Ingredients:</strong><br/>
      <% @recipe.recipe_items.each do |recipe_item| %>
        <%= "#{recipe_item.amount} #{recipe_item.ingredient.name}" %><br/>
      <% end %>
    </p>

    <p>
      <strong>Instructions:</strong><br/>
      <% @instructions.each do |instruction| %>
        <%= instruction %><br/>
      <% end %>
    </p>
    <br/>
    <%= link_to 'Back', recipes_path, class: "btn btn-default" %>
    <%= link_to 'Edit', edit_recipe_path(@recipe), class: "btn btn-info" %>
    <%= link_to 'Destroy', recipe_path(@recipe),
        method: :delete,
        data: { confirm: 'For real?' },
        class: "btn btn-danger" %>
  </div>
</div>

app/views/static_pages/about.html.erb
<div class="container">
  <div class="jumbotron">
    <h2 class="page-heading">About</h2>
    <br/>
    <p>This is an app I'm learning to make using rails.</p>
    <p>The repo can be found 
    <a href="https://github.com/mostlybadfly/recetera" class="gitlink">here</a>
    </p>
  </div>
</div>

app/views/static_pages/welcome.html.erb
<div class="container">
  <div class="jumbotron">
    <h2 class="page-heading">Welcome to Recetera!</h2>
    <br/>
    <p>This is a recipe-making app, check back soon for more updates!</p>
    <br/>
    <%= link_to 'New recipe', new_recipe_path, :class => "btn btn-info"  %>

    <%= link_to 'All recipes', recipes_path, :class => "btn btn-info"  %>
  </div>
</div>

app/views/user/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h2><%= @user.email %>'s Recipes</h2>
    <h3> Published Recipes </h3>
    <% @user.recipes.published_recipes.each do |recipe| %>
      <ul class="list-unstyled">
        <li>
          <%= link_to recipe.title, recipe_path(recipe) %>
        </li>
      </ul>
    <% end %>
    <h3> Unpublished Recipes </h3>
    <% @user.recipes.unpublished_recipes.each do |recipe| %>
      <ul class="list-unstyled">
        <li>
          <%= link_to recipe.title, recipe_path(recipe) %>
        </li>
      </ul>
    <% end %>
    <br>
    <%= link_to "Account Settings", edit_user_registration_path, :class => "btn btn-sm btn-warning pull-right" %>
  </div>
</div>